extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- admonition
- footnotes
- meta
- pymdownx.caret
- pymdownx.tilde
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.arithmatex:
    generic: true
- codehilite:
    guess_lang: false
    linenums: true
- toc:
    permalink: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.tasklist:
    custom_checkbox: true
nav:
- docs:
  - guide.md
  - index.md
- healthy:
  - healthy/behavior.md
- cuda:
  - cuda/cmd.md
  - cuda/other.md
  - cuda/profile.md
  - cuda/tilelang.md
- triton:
  - triton/basic.md
- algorithm:
  - algorithm/merkle.md
- daily:
  - daily/0327.md
  - daily/0328.md
  - daily/0331.md
  - daily/0401.md
- search:
  - search/basic.md
  - search/search_engine.md
  - search/spelling_correction.md
  - search/theone_search_design.md
  - search/theone_search_design_impl.md
- bitcoin:
  - bitcoin/basic.md
  - bitcoin/bull_bear.md
  - bitcoin/chains.md
  - bitcoin/consensus.md
  - bitcoin/lean_chain.md
  - bitcoin/nft_mint.md
  - bitcoin/norms.md
  - bitcoin/pos.md
  - bitcoin/problem.md
  - bitcoin/solana.md
  - bitcoin/story.md
  - bitcoin/theory.md
  - bitcoin/tps.md
- train:
  - train/unsloth.md
- cc:
  - cc/cudac.md
  - cc/mix.md
  - cc/smart_point.md
  - cc/type_erasure.md
  - cc/xapian.md
- bitcoin/nft:
  - bitcoin/nft/qa.md
  - bitcoin/nft/text_nft.md
  - bitcoin/nft/text_nft_anti.md
plugins:
- search:
    separator: '[\s\-\.]+'
site_name: zwy notes
theme:
  features:
  - search.suggest
  - search.highlight
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - content.code.copy
  name: readthedocs
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
