markdown_extensions:
- admonition
- footnotes
- meta
- pymdownx.caret
- pymdownx.tilde
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- codehilite:
    guess_lang: false
    linenums: true
- toc:
    permalink: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.tasklist:
    custom_checkbox: true
nav:
- docs:
  - guide.md
  - index.md
- healthy:
  - healthy/behavior.md
- daily:
  - daily/0327.md
  - daily/0328.md
  - daily/0331.md
- search:
  - search/search_engine.md
  - search/spelling_correction.md
  - search/theone_search_design.md
  - search/theone_search_design_impl.md
- train:
  - train/unsloth.md
- cc:
  - cc/cudac.md
  - cc/mix.md
  - cc/smart_point.md
  - cc/type_erasure.md
plugins:
- search:
    separator: '[\s\-\.]+'
site_name: zwy notes
theme:
  features:
  - search.suggest
  - search.highlight
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - content.code.copy
  name: readthedocs
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
